---
kind: pipeline
type: docker
name: default
    
steps: 
- name: build
  image: maven:3-jdk-11
  commands:
  - mvn -Dmaven.test.skip=true assembly:assembly
- name: unittests
  image: maven:3-jdk-11 
  commands:
  - mvn test
- name: pmd
  image: rawdee/pmd
  commands:
  - pmd -d src/main/java -f text -R pmd_ruleset.xml -language java
- name: publish
  image: plugins/docker
  settings:
    repo: thekellner/calculator
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_token
